#!/bin/bash

# Adpated from https://gist.github.com/ef4/2075048

OUTPUT="alsa_output.hw_CARD_Wireless_DEV_1"
INPUT="alsa_input.usb-SteelSeries_Arctis_Pro_Wireless-00.analog-mono"

if [ "$1" == "--fork" ]; then
    # When run from udev, we fork to give pulseaudio a chance to
    # detect the new device
    bash "$0" &
elif [ "$UID" == "0" ]; then
    # If we're running as root, we just forked from udev. Now sleep so
    # pulseaudio can run.
    sleep 1
 
    # Check process table for users running PulseAudio
    for user in $(ps axc -o user,command | grep pulseaudio | cut -f1 -d' ' | sort | uniq);
    do
	    # And relaunch ourselves for each of those users.
	    su "$user" -c "bash $0" &
    done
else
    # Running as non-root, so adjust our PulseAudio directly.
    pacmd set-default-sink $OUTPUT >/dev/null 2>&1
    pacmd set-default-source $INPUT >/dev/null 2>&1

    for playing in $(pacmd list-sink-inputs | awk '$1 == "index:" {print $2}')
    do
	    pacmd move-sink-input "$playing" $OUTPUT >/dev/null 2>&1
    done

    for recording in $(pacmd list-source-outputs | awk '$1 == "index:" {print $2}')
    do
	    pacmd move-source-output "$recording" $INPUT >/dev/null 2>&1
    done    
fi

# Set the volume of the ALSA sound card to maximum
if [[ "$*" == *"--alsa-max-volume"* ]]; then
    # Escaped pattern of card to look for in aplay's output
    CARD_PATTERN="Wireless \[Arctis Pro Wireless\]"
    # Control patterns to look for in amixer's output for mono and stereo (chat and game)
    CONTROL_PATTERNS=("name='PCM Playback Volume'" "name='PCM Playback Volume',index=1")

    # Extract card number form output
    CARD_NUM=$(aplay -l | grep -oP "(?<=card )\d+(?=:.*$CARD_PATTERN)" | head -n 1)
    if [ -z "$CARD_NUM" ]; then
        echo "Sound card not found"
        exit 1
    fi
    echo "Found device with sound card number $CARD_NUM"

    for CONTROL_PATTERN in "${CONTROL_PATTERNS[@]}"
    do
        # Extract control number from output
        CONTROL_NUM=$(amixer -c "$CARD_NUM" controls | grep -oP "(?<=^numid=)\d+(?=.*$CONTROL_PATTERN$)")
        if [ -z "$CONTROL_NUM" ]; then
            echo "Control $CONTROL_PATTERN not found for card"
            exit 1
        fi
        echo "Found control with numid=$CONTROL_NUM"

        amixer -c "$CARD_NUM" cset "numid=$CONTROL_NUM" 100%
        echo "Volume set to 100% for $CONTROL_PATTERN"
    done
fi